//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcumaticaServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.acumatica.com/untyped/", ConfigurationName="AcumaticaServiceReference.ScreenSoap")]
    public interface ScreenSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/Clear", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task ClearAsync(string screenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/GetProcessStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        System.Threading.Tasks.Task<AcumaticaServiceReference.ProcessResult> GetProcessStatusAsync(string screenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/GetScenario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        System.Threading.Tasks.Task<AcumaticaServiceReference.Command[]> GetScenarioAsync(string scenario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/GetSchema", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        System.Threading.Tasks.Task<AcumaticaServiceReference.Content> GetSchemaAsync(string screenID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/SetSchema", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        System.Threading.Tasks.Task SetSchemaAsync(string screenID, AcumaticaServiceReference.Content schema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/Export", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        System.Threading.Tasks.Task<AcumaticaServiceReference.ExportResponse> ExportAsync(AcumaticaServiceReference.ExportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/Import", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        System.Threading.Tasks.Task<AcumaticaServiceReference.ImportResponse> ImportAsync(AcumaticaServiceReference.ImportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/Submit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        System.Threading.Tasks.Task<AcumaticaServiceReference.Content[]> SubmitAsync(string screenID, AcumaticaServiceReference.Command[] commands);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        System.Threading.Tasks.Task<AcumaticaServiceReference.LoginResult> LoginAsync(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        System.Threading.Tasks.Task LogoutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/SetBusinessDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        System.Threading.Tasks.Task SetBusinessDateAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/SetLocaleName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        System.Threading.Tasks.Task SetLocaleNameAsync(string localeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.acumatica.com/untyped/SetSchemaMode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Filter[]))]
        System.Threading.Tasks.Task SetSchemaModeAsync(AcumaticaServiceReference.SchemaMode mode);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class ProcessResult
    {
        
        private ProcessStatus statusField;
        
        private int secondsField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ProcessStatus Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Seconds
        {
            get
            {
                return this.secondsField;
            }
            set
            {
                this.secondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public enum ProcessStatus
    {
        
        /// <remarks/>
        NotExists,
        
        /// <remarks/>
        InProcess,
        
        /// <remarks/>
        Completed,
        
        /// <remarks/>
        Aborted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class LoginResult
    {
        
        private ErrorCode codeField;
        
        private string messageField;
        
        private string sessionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ErrorCode Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public enum ErrorCode
    {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        INVALID_CREDENTIALS,
        
        /// <remarks/>
        INTERNAL_ERROR,
        
        /// <remarks/>
        INVALID_API_VERSION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class ImportResult
    {
        
        private bool processedField;
        
        private string errorField;
        
        private Value[] keysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Processed
        {
            get
            {
                return this.processedField;
            }
            set
            {
                this.processedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Value[] Keys
        {
            get
            {
                return this.keysField;
            }
            set
            {
                this.keysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Value : Field
    {
        
        private string messageField;
        
        private bool isErrorField;
        
        private string errorLevelField;
        
        public Value()
        {
            this.isErrorField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsError
        {
            get
            {
                return this.isErrorField;
            }
            set
            {
                this.isErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorLevel
        {
            get
            {
                return this.errorLevelField;
            }
            set
            {
                this.errorLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Attachment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Value))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Field : Command
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Key))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Answer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Action))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Parameter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NewRow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeleteRow))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RowNumber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EveryValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Field))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Attachment))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Value))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Command
    {
        
        private string fieldNameField;
        
        private string objectNameField;
        
        private string valueField;
        
        private bool commitField;
        
        private bool ignoreErrorField;
        
        private Command linkedCommandField;
        
        private string nameField;
        
        private ElementDescriptor descriptorField;
        
        public Command()
        {
            this.commitField = false;
            this.ignoreErrorField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FieldName
        {
            get
            {
                return this.fieldNameField;
            }
            set
            {
                this.fieldNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ObjectName
        {
            get
            {
                return this.objectNameField;
            }
            set
            {
                this.objectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Commit
        {
            get
            {
                return this.commitField;
            }
            set
            {
                this.commitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IgnoreError
        {
            get
            {
                return this.ignoreErrorField;
            }
            set
            {
                this.ignoreErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Command LinkedCommand
        {
            get
            {
                return this.linkedCommandField;
            }
            set
            {
                this.linkedCommandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public ElementDescriptor Descriptor
        {
            get
            {
                return this.descriptorField;
            }
            set
            {
                this.descriptorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class ElementDescriptor
    {
        
        private string displayNameField;
        
        private bool isDisabledField;
        
        private bool isRequiredField;
        
        private ElementTypes elementTypeField;
        
        private int lengthLimitField;
        
        private string inputMaskField;
        
        private string displayRulesField;
        
        private string[] allowedValuesField;
        
        private Container containerField;
        
        private string actionIconField;
        
        private int fieldPriorityField;
        
        private PXSpecialButtonType buttonTypeField;
        
        private string linkCommandField;
        
        private bool visibleField;
        
        private bool isTimeListField;
        
        private System.Nullable<bool> preserveTimeField;
        
        private string dependsOnField;
        
        private string stateColumnField;
        
        public ElementDescriptor()
        {
            this.isDisabledField = false;
            this.isRequiredField = false;
            this.elementTypeField = ElementTypes.String;
            this.lengthLimitField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DisplayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsDisabled
        {
            get
            {
                return this.isDisabledField;
            }
            set
            {
                this.isDisabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsRequired
        {
            get
            {
                return this.isRequiredField;
            }
            set
            {
                this.isRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(ElementTypes.String)]
        public ElementTypes ElementType
        {
            get
            {
                return this.elementTypeField;
            }
            set
            {
                this.elementTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int LengthLimit
        {
            get
            {
                return this.lengthLimitField;
            }
            set
            {
                this.lengthLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string InputMask
        {
            get
            {
                return this.inputMaskField;
            }
            set
            {
                this.inputMaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DisplayRules
        {
            get
            {
                return this.displayRulesField;
            }
            set
            {
                this.displayRulesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public string[] AllowedValues
        {
            get
            {
                return this.allowedValuesField;
            }
            set
            {
                this.allowedValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Container Container
        {
            get
            {
                return this.containerField;
            }
            set
            {
                this.containerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ActionIcon
        {
            get
            {
                return this.actionIconField;
            }
            set
            {
                this.actionIconField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int FieldPriority
        {
            get
            {
                return this.fieldPriorityField;
            }
            set
            {
                this.fieldPriorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public PXSpecialButtonType ButtonType
        {
            get
            {
                return this.buttonTypeField;
            }
            set
            {
                this.buttonTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string LinkCommand
        {
            get
            {
                return this.linkCommandField;
            }
            set
            {
                this.linkCommandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool Visible
        {
            get
            {
                return this.visibleField;
            }
            set
            {
                this.visibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool IsTimeList
        {
            get
            {
                return this.isTimeListField;
            }
            set
            {
                this.isTimeListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<bool> PreserveTime
        {
            get
            {
                return this.preserveTimeField;
            }
            set
            {
                this.preserveTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string DependsOn
        {
            get
            {
                return this.dependsOnField;
            }
            set
            {
                this.dependsOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string StateColumn
        {
            get
            {
                return this.stateColumnField;
            }
            set
            {
                this.stateColumnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public enum ElementTypes
    {
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        AsciiString,
        
        /// <remarks/>
        StringSelector,
        
        /// <remarks/>
        ExplicitSelector,
        
        /// <remarks/>
        Number,
        
        /// <remarks/>
        Option,
        
        /// <remarks/>
        WideOption,
        
        /// <remarks/>
        Calendar,
        
        /// <remarks/>
        Action,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Container
    {
        
        private Field[] fieldsField;
        
        private string nameField;
        
        private Command[] serviceCommandsField;
        
        private Container[] childrenField;
        
        private string displayNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Field[] Fields
        {
            get
            {
                return this.fieldsField;
            }
            set
            {
                this.fieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Command[] ServiceCommands
        {
            get
            {
                return this.serviceCommandsField;
            }
            set
            {
                this.serviceCommandsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public Container[] Children
        {
            get
            {
                return this.childrenField;
            }
            set
            {
                this.childrenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DisplayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public enum PXSpecialButtonType
    {
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        Save,
        
        /// <remarks/>
        SaveNotClose,
        
        /// <remarks/>
        Cancel,
        
        /// <remarks/>
        Refresh,
        
        /// <remarks/>
        CopyPaste,
        
        /// <remarks/>
        Report,
        
        /// <remarks/>
        First,
        
        /// <remarks/>
        Next,
        
        /// <remarks/>
        Prev,
        
        /// <remarks/>
        Last,
        
        /// <remarks/>
        Insert,
        
        /// <remarks/>
        Delete,
        
        /// <remarks/>
        Approve,
        
        /// <remarks/>
        ApproveAll,
        
        /// <remarks/>
        Process,
        
        /// <remarks/>
        ProcessAll,
        
        /// <remarks/>
        Schedule,
        
        /// <remarks/>
        EditDetail,
        
        /// <remarks/>
        ActionsFolder,
        
        /// <remarks/>
        InquiriesFolder,
        
        /// <remarks/>
        ReportsFolder,
        
        /// <remarks/>
        ToolbarFolder,
        
        /// <remarks/>
        SidePanelFolder,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Key : Command
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Answer : Command
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Action : Command
    {
        
        private string viewTypeNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ViewTypeName
        {
            get
            {
                return this.viewTypeNameField;
            }
            set
            {
                this.viewTypeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Parameter : Command
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class NewRow : Command
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class DeleteRow : Command
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class RowNumber : Command
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class EveryValue : Command
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Attachment : Field
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Filter
    {
        
        private Field fieldField;
        
        private FilterCondition conditionField;
        
        private object valueField;
        
        private object value2Field;
        
        private int openBracketsField;
        
        private int closeBracketsField;
        
        private FilterOperator operatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Field Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FilterCondition Condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public object Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public object Value2
        {
            get
            {
                return this.value2Field;
            }
            set
            {
                this.value2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int OpenBrackets
        {
            get
            {
                return this.openBracketsField;
            }
            set
            {
                this.openBracketsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int CloseBrackets
        {
            get
            {
                return this.closeBracketsField;
            }
            set
            {
                this.closeBracketsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public FilterOperator Operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public enum FilterCondition
    {
        
        /// <remarks/>
        Equals,
        
        /// <remarks/>
        NotEqual,
        
        /// <remarks/>
        Greater,
        
        /// <remarks/>
        GreaterOrEqual,
        
        /// <remarks/>
        Less,
        
        /// <remarks/>
        LessOrEqual,
        
        /// <remarks/>
        Contain,
        
        /// <remarks/>
        StartsWith,
        
        /// <remarks/>
        EndsWith,
        
        /// <remarks/>
        NotContain,
        
        /// <remarks/>
        Between,
        
        /// <remarks/>
        IsNull,
        
        /// <remarks/>
        IsNotNull,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public enum FilterOperator
    {
        
        /// <remarks/>
        And,
        
        /// <remarks/>
        Or,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public partial class Content
    {
        
        private Action[] actionsField;
        
        private Container[] containersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Action[] Actions
        {
            get
            {
                return this.actionsField;
            }
            set
            {
                this.actionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Container[] Containers
        {
            get
            {
                return this.containersField;
            }
            set
            {
                this.containersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Export", WrapperNamespace="http://www.acumatica.com/untyped/", IsWrapped=true)]
    public partial class ExportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=0)]
        public string screenID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=1)]
        public AcumaticaServiceReference.Command[] commands;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=2)]
        public AcumaticaServiceReference.Filter[] filters;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=3)]
        public int topCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=4)]
        public bool includeHeaders;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=5)]
        public bool breakOnError;
        
        public ExportRequest()
        {
        }
        
        public ExportRequest(string screenID, AcumaticaServiceReference.Command[] commands, AcumaticaServiceReference.Filter[] filters, int topCount, bool includeHeaders, bool breakOnError)
        {
            this.screenID = screenID;
            this.commands = commands;
            this.filters = filters;
            this.topCount = topCount;
            this.includeHeaders = includeHeaders;
            this.breakOnError = breakOnError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportResponse", WrapperNamespace="http://www.acumatica.com/untyped/", IsWrapped=true)]
    public partial class ExportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] ExportResult;
        
        public ExportResponse()
        {
        }
        
        public ExportResponse(string[][] ExportResult)
        {
            this.ExportResult = ExportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Import", WrapperNamespace="http://www.acumatica.com/untyped/", IsWrapped=true)]
    public partial class ImportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=0)]
        public string screenID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=1)]
        public AcumaticaServiceReference.Command[] commands;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=2)]
        public AcumaticaServiceReference.Filter[] filters;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=4)]
        public bool includedHeaders;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=5)]
        public bool breakOnError;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=6)]
        public bool breakOnIncorrectTarget;
        
        public ImportRequest()
        {
        }
        
        public ImportRequest(string screenID, AcumaticaServiceReference.Command[] commands, AcumaticaServiceReference.Filter[] filters, string[][] data, bool includedHeaders, bool breakOnError, bool breakOnIncorrectTarget)
        {
            this.screenID = screenID;
            this.commands = commands;
            this.filters = filters;
            this.data = data;
            this.includedHeaders = includedHeaders;
            this.breakOnError = breakOnError;
            this.breakOnIncorrectTarget = breakOnIncorrectTarget;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportResponse", WrapperNamespace="http://www.acumatica.com/untyped/", IsWrapped=true)]
    public partial class ImportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.acumatica.com/untyped/", Order=0)]
        public AcumaticaServiceReference.ImportResult[] ImportResult;
        
        public ImportResponse()
        {
        }
        
        public ImportResponse(AcumaticaServiceReference.ImportResult[] ImportResult)
        {
            this.ImportResult = ImportResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.acumatica.com/untyped/")]
    public enum SchemaMode
    {
        
        /// <remarks/>
        Basic,
        
        /// <remarks/>
        Detailed,
        
        /// <remarks/>
        DetailedWithHidden,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ScreenSoapChannel : AcumaticaServiceReference.ScreenSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ScreenSoapClient : System.ServiceModel.ClientBase<AcumaticaServiceReference.ScreenSoap>, AcumaticaServiceReference.ScreenSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ScreenSoapClient() : 
                base(ScreenSoapClient.GetDefaultBinding(), ScreenSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ScreenSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ScreenSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ScreenSoapClient.GetBindingForEndpoint(endpointConfiguration), ScreenSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ScreenSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ScreenSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ScreenSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ScreenSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ScreenSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task ClearAsync(string screenID)
        {
            return base.Channel.ClearAsync(screenID);
        }
        
        public System.Threading.Tasks.Task<AcumaticaServiceReference.ProcessResult> GetProcessStatusAsync(string screenID)
        {
            return base.Channel.GetProcessStatusAsync(screenID);
        }
        
        public System.Threading.Tasks.Task<AcumaticaServiceReference.Command[]> GetScenarioAsync(string scenario)
        {
            return base.Channel.GetScenarioAsync(scenario);
        }
        
        public System.Threading.Tasks.Task<AcumaticaServiceReference.Content> GetSchemaAsync(string screenID)
        {
            return base.Channel.GetSchemaAsync(screenID);
        }
        
        public System.Threading.Tasks.Task SetSchemaAsync(string screenID, AcumaticaServiceReference.Content schema)
        {
            return base.Channel.SetSchemaAsync(screenID, schema);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AcumaticaServiceReference.ExportResponse> AcumaticaServiceReference.ScreenSoap.ExportAsync(AcumaticaServiceReference.ExportRequest request)
        {
            return base.Channel.ExportAsync(request);
        }
        
        public System.Threading.Tasks.Task<AcumaticaServiceReference.ExportResponse> ExportAsync(string screenID, AcumaticaServiceReference.Command[] commands, AcumaticaServiceReference.Filter[] filters, int topCount, bool includeHeaders, bool breakOnError)
        {
            AcumaticaServiceReference.ExportRequest inValue = new AcumaticaServiceReference.ExportRequest();
            inValue.screenID = screenID;
            inValue.commands = commands;
            inValue.filters = filters;
            inValue.topCount = topCount;
            inValue.includeHeaders = includeHeaders;
            inValue.breakOnError = breakOnError;
            return ((AcumaticaServiceReference.ScreenSoap)(this)).ExportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AcumaticaServiceReference.ImportResponse> AcumaticaServiceReference.ScreenSoap.ImportAsync(AcumaticaServiceReference.ImportRequest request)
        {
            return base.Channel.ImportAsync(request);
        }
        
        public System.Threading.Tasks.Task<AcumaticaServiceReference.ImportResponse> ImportAsync(string screenID, AcumaticaServiceReference.Command[] commands, AcumaticaServiceReference.Filter[] filters, string[][] data, bool includedHeaders, bool breakOnError, bool breakOnIncorrectTarget)
        {
            AcumaticaServiceReference.ImportRequest inValue = new AcumaticaServiceReference.ImportRequest();
            inValue.screenID = screenID;
            inValue.commands = commands;
            inValue.filters = filters;
            inValue.data = data;
            inValue.includedHeaders = includedHeaders;
            inValue.breakOnError = breakOnError;
            inValue.breakOnIncorrectTarget = breakOnIncorrectTarget;
            return ((AcumaticaServiceReference.ScreenSoap)(this)).ImportAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<AcumaticaServiceReference.Content[]> SubmitAsync(string screenID, AcumaticaServiceReference.Command[] commands)
        {
            return base.Channel.SubmitAsync(screenID, commands);
        }
        
        public System.Threading.Tasks.Task<AcumaticaServiceReference.LoginResult> LoginAsync(string name, string password)
        {
            return base.Channel.LoginAsync(name, password);
        }
        
        public System.Threading.Tasks.Task LogoutAsync()
        {
            return base.Channel.LogoutAsync();
        }
        
        public System.Threading.Tasks.Task SetBusinessDateAsync(System.DateTime date)
        {
            return base.Channel.SetBusinessDateAsync(date);
        }
        
        public System.Threading.Tasks.Task SetLocaleNameAsync(string localeName)
        {
            return base.Channel.SetLocaleNameAsync(localeName);
        }
        
        public System.Threading.Tasks.Task SetSchemaModeAsync(AcumaticaServiceReference.SchemaMode mode)
        {
            return base.Channel.SetSchemaModeAsync(mode);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ScreenSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ScreenSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/SalesDemo20R2/Soap/.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ScreenSoapClient.GetBindingForEndpoint(EndpointConfiguration.ScreenSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ScreenSoapClient.GetEndpointAddress(EndpointConfiguration.ScreenSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            ScreenSoap,
        }
    }
}
